export const PLAYED_CORRECT_DEFINITION = 3;
export const VOTED_CORRECT_DEFINITION = 2;
export const OTHER_PLAYER_VOTED_YOUR_DEFINITION = 1;
export const NO_PLAYER_PLAYED_OR_VOTED_CORRECT_DEFINITION = 3;
